name: Cypress Tests for http://test-engineer.online/
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
  
   - name: Install dependencies
      run: npm install
  
  - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npm run live
 
    - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npm run cypress:run:test